version: '3.8'
services:
  quiz-app-client:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
      # args:
      #   - ENV_VARIABLE=thiswillbepassedtodockerfile.prod
    ports:
      - "8080:80"
    # env_file:
    #   - ./.env