FROM node as build
WORKDIR /client
COPY package.json .
RUN npm install
COPY . .
# ARG ENV_VARIABLE
# ENV ENV_VARIABLE=$ENV_VARIABLE
RUN npm run build

FROM nginx
COPY --from=build /client/build /usr/share/nginx/html